[package]
name = "hello_world_aws"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.5"
aws-sdk-ec2 = "1.70.0"
ratatui = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
